---
apiVersion: v1
kind: Service
metadata:
  name: video-slicer-auth
  namespace: video-slicer-auth-api
  labels:
    app: video-slicer-auth
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: video-slicer-auth
  type: LoadBalancer